[package]
name = "workspace"
version = "0.1.0"
edition = "2021"

[dependencies]
rtsyn_plugin = { workspace = true }
connection = { path = "../connection" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
